const o = {
  dashboardTabs: {
    FormBuilders: "Formulario"
  },
  sections: {
    forms: "Formulario"
  },
  formPicker: {
    selectFromFolder: "Seleccionar de la carpeta",
    selectFromList: "Seleccionar de la lista de todos los formularios",
    removeItemButtonLabel: "Eliminar formulario '{0}'",
    form: "Forma",
    theme: "Tema",
    redirectToPage: "Redirigir a la página después del envío del formulario",
    redirectToPageDescription: "Si no se proporciona, se utilizará la visualización del mensaje o el comportamiento de redireccionamiento definido en el formulario.."
  },
  formsDashboard: {
    yourForms: "Tu formularios",
    showMore: "Muestra más",
    entries: "Entradas",
    newVersion: "Hay una nueva versión disponible",
    installOverlayTitle: "Felicidades",
    installOverlayDescription: "Acabas de instalar Umbraco Forms - Vamos a crear tu primera forma",
    emptyOverlayTitle: "Crear un formulario",
    emptyOverlayDescription: "Aún no tienes ningún formulario configurado, que dices si creas uno ahora?",
    createAForm: "Crear un formulario",
    newVersionTitle: "Hay una nueva versión disponible",
    newVersionDescription: "Ahora puedes instalar Umbraco Forms",
    upgradeNow: "Actualizar ahora",
    downloading: "Descargar y actualizar formularios...",
    invalidLicense: "Licencia invalida",
    invalidLicenseValidFor: "Tu licencia de Formularios actual solo es válida para:",
    reconfigure: "Por favor, regresa a configurar tu licencia a continuación.",
    trialTitle: "Gracias por probar Umbraco Forms",
    trialDescription: "Para seguir usando Umbraco Forms, debes comprar una licencia o usar una licencia existente",
    configureLicense: "Configurar la licencia existente",
    buyLicense: "Compra licencia",
    buyLicenseTitle: "Comprar una licencia",
    buyLicenseCopy: `
        <p>
          Solo toma <strong>unos minutos comprar una licencia para</strong> for Umbraco Forms and your <strong>y tu licencia se entrega instantáneamente</strong>.
        </p>
        <p>
          Los pasos son:
          <ol>
            <li>Haga clic en el botón de compras a continuación</li>
            <li>Pago con tarjeta de crédito (o factura)</li>
            <li>Configure la licencia dentro de Umbraco Forms y vas a estar en funcionamiento</li>
          </ol>
        </p>
    `,
    buyLink: "Compra Umbraco Forms",
    buyLicenseFAQs: `
        <h4>Preguntas frecuentes:</h4>
        <h5>¿Cuanto cuesta?</h5>
        <p>Los precios comienzan en &euro;209 y es un pago único (sin suscripción).</p>
        <h5>¿Qué cubre una licencia?</h5>
        <p>Una licencia cubre un solo dominio y también funcionará en todos los subdominios. It also includes two additional development domains.</p>
        <h5>¿Puedo agregar dominios adicionales a la licencia?</h5>
        <p>Sí, se pueden agregar dominios adicionales. Puedes comprar dominios adicionales a tu licencia desde tu cuenta en Umbraco.com.</p>
        <h5>¿Más preguntas</h5>
        <p>
          No te preocupes, hay <a class="green-link" href="https://docs.umbraco.com/other-resources/the-licensing-model">más detalles en la documentación</a> Y también eres más que bienvenido/a <a class="green-link" href="https://umbraco.com/contact-us?utm_source=core&utm_medium=dashboard&utm_content=contact-us-link&utm_campaign=formslicensing">a ponerte en contacto con nosotros</a>. Generalmente respondemos en un par de horas.
        </p>
    `,
    configureLicenseTitle: "Configurar una licencia de Umbraco Forms",
    configureLicenseCopy: `
      Si ya has comprado Umbraco Forms, puedes recuperar y configurar tu licencia automáticamente aquí. Simplemente ingrese sus credenciales de umbraco.com debajo
      y encontraremos tu licencia.
    `,
    configureLicenseFAQs: `
        <h4>Preguntas frecuentes:</h4>
        <h5>¿No sé cuáles son mis credenciales?</h5>
        <p>
          Es una combinación de tu correo electrónico y contraseña desde el momento en que el pedido fue realizado. Siempre puedes <a class="green-link" href="https://shop.umbraco.com/profile/retrieve-your-password/:">restablecer tu contraseña aquí</a>.
        </p>
        <h5>¿Cómo compro una licencia?</h5>
        <p>
         Si no tienes una licencia, puedes <a href="https://shop.umbraco.com/shop/cart/?p=6201&direct=true&utm_source=core&utm_medium=dashboard&utm_content=topic-link&utm_campaign=formslicensing" target="_blank">obtener una desde aquí y solo te llevará unos minutos</a>.
        </p>
    `,
    findLicenses: "Encontrar licencias",
    invalidEmail: "Email o contraseña inválidos",
    noLicensesAvailable: "No hay licencias de Umbraco Forms disponibles en esta cuenta",
    availableLicensesTitle: "Licencias Disponibles",
    foundLicenses: "Encontrada",
    foundLicensesAccount: "en la cuenta",
    noDomainsAssigned: "No tiene dominios asignados",
    setDomain: "Por favor configure un dominio en esta licencia",
    configureAndInstall: "Configurar e instalar",
    installLicense: "Instalar esta licencia",
    validDomains: "Dominios válidos",
    licenseValidOnDomain: "Esta licencia es válida en el dominio actual",
    licenseNotValidOnDomain: "Esta licencia es válida en el dominio actual",
    plainTextPasswordWarning: `
        <h3 class="warning">Advertencia: tus ajustes de configuración están configurados para guardar contraseñas de texto sin formato.</h3>
        <p>Cuando utilizas un campo de contraseña en cualquiera de tus formularios, los datos que tus visitantes ingresarán en ese campo se almacenarán en texto sin formato. Este es un problema de seguridad y debe evitarse.</p>
        <p>Para solucionar este problema, puede ir a tu <span class="code:">~/App_Plugins/FormBuilder/FormBuilder.config</span> archivo y establecer la clave <span class="code:">SavePlainTextPasswords</span> en <span class="code">Falso</span>.</p>
        <p>Después de actualizar esta configuración, asegúrese de reciclar el grupo de aplicaciones del sitio para que la nueva configuración se active.</p>
        <p>Nota: los valores de contraseña se seguirán transmitiendo a los flujos de trabajo, independientemente de la configuración en <span class="code">FormBuilder.config</span></p>
    `,
    currentVersion: "La versión actual instalada de Umbraco Forms:",
    licenseConfiguredNotificationTitle: "Licencia configurada",
    licenseConfiguredNotificationMessage: "Umbraco Forms se ha configurado para tu uso en este sitio web.",
    insufficientPermissionsError: "Permisos insuficientes",
    insufficientPermissionsMessage: "No tienes permisos para crear y administrar formularios.",
    insufficientPermissionsUpgradeMessage: "Solo los usuarios administradores pueden actualizar los formularios Umbraco.",
    licensedDomains: "Dominios con licencia"
  },
  formCopy: {
    modalHeadline: "Copiar formulario",
    title: (e) => `Copiando formulario '${e}'`,
    enterName: "Ingresa un nombre para el formulario copiado",
    enterNewName: "Introduce un nuevo nombre...",
    alsoCopyWorkflows: "¿Quieres copiar también los flujos de trabajo?",
    copyToNewFolder: "¿Copiar a una carpeta nueva?",
    selectLocation: "Selecciona la ubicación del formulario copiado",
    mandatoryWorkflowsCopied: "Los flujos de trabajo obligatorios siempre se copiarán.",
    copy: "Copiar",
    copySuccess: "Formulario copiado exitosamente.",
    copyError: "Se produjo un error al copiar el formulario.."
  },
  formCopyWorkflows: {
    title: "Copiar flujos de trabajo",
    subtitle: "Copiar flujos de trabajo de '%0%'",
    noWorkflows: "El formulario no contiene ningún flujo de trabajo.",
    selectedWorkflows: "Los siguientes flujos de trabajo están asignados al formulario. Por favor confirme los que desea copiar:",
    stage: "Etapa",
    selected: "Seleccionado",
    destinationForm: "Seleccione el formulario al que desea copiar los flujos de trabajo::",
    selectedDestinationForm: "Formulario de destino seleccionado: <b>%0%</b>",
    selectAnotherForm: "seleccione otra forma",
    copiedWorkflowsSuccess: "Los flujos de trabajo se copiaron al formulario seleccionado.",
    copiedWorkflowsError: "Se produjo un error al copiar flujos de trabajo del formulario seleccionado."
  },
  formCreate: {
    title: "Ccrear un nuevo formulario o carpeta",
    emptyForm: "Formulario vacío",
    emptyFormDescription: "Empezando de nuevo",
    folder: "Carpeta",
    folderDescription: "Utilizado para organizar formularios",
    enterFolderName: "Ingrese un nombre de carpeta",
    newFormMenu: "Nueva forma...",
    newFolderMenu: "Nueva carpeta..."
  },
  formExport: {
    exportInstruction: "Haga clic para exportar el formulario seleccionado a un archivo..",
    formExportedSuccess: "El formulario fue exportado a un archivo..",
    formExportedError: "Se produjo un error al guardar el formulario en un archivo."
  },
  formImport: {
    importInstruction1: "Para importar un formulario, busque el archivo .json exportado en su computadora haciendo clic en el botón 'Importar' (se le pedirá confirmación en la siguiente pantalla).",
    importInstruction2: `Si ya existe un formulario con el ID del archivo seleccionado, se actualizará y se moverá a la ubicación seleccionada.
      Si no se encuentra ningún formulario existente, se creará uno nuevo en la ubicación seleccionada.`
  },
  formPermissions: {
    accessDeniedTitle: "Acceso denegado"
  },
  formMessages: {
    saveErrorMessage: "Por favor, compruebe si tu configuración es válida."
  },
  formEdit: {
    addQuestion: "Añadir pregunta",
    groupIsEmpty: "El grupo está vacío",
    dropQuestionHere: "Deja una pregunta aquí...",
    letGo: "Yaay.. vamonos",
    pageIsEmpty: "La página esta vacía",
    dropGroupHere: "Pon un grupo aquí...",
    addGroup: "Agregar un grupo nuevo",
    addPage: "Agregar página nuevae",
    pageTitlePlaceholder: "Página sin título (opcional)",
    groupTitlePlaceholder: "Grupo sin título (opcional)",
    groupTitlePlaceholderMandatory: "Grupo sin título group",
    saveFieldFailedTitle: "El campo no se pudo guardar",
    accessDeniedMessage: "No tienes acceso para editar este formulario.",
    formSaved: "Formulario guardado",
    formSaveFailed: "Error al guardar el formulario",
    unableToLoadForm: "No se puede cargar el formulario",
    helpText: "Texto de ayuda",
    editPage: "Editar página",
    editGroup: "Editar grupo",
    editQuestion: "Editar pregunta",
    workflows: "Flujos de trabajo",
    magicStringsForFieldsNote: `
      Muchas configuraciones de flujo de trabajo admiten el uso de <b>cadenas mágicas</b>.
      Cuando se procesa el flujo de trabajo, estas cadenas se pueden reemplazar con valores de varias fuentes, incluidos datos de registro y valores de diccionario.
      <a href="https://docs.umbraco.com/umbraco-forms/developer/magic-strings" target="_blank">"Lee mas</a>.
    `,
    magicStringsForWorkflowsNote: `
      Many workflow settings support the use of <b>magic strings</b>.
      When the workflow is processed, these strings can be replaced with values from various sources, including record data and dictionary values.
      <a href="https://docs.umbraco.com/umbraco-forms/developer/magic-strings" target="_blank">"Lee mas</a>.
    `,
    fieldTypeNotAvailable: "El tipo de campo configurado para este campo ya no está disponible.",
    fieldTypeRichTextNotAvailable: "El texto enriquecido no se puede formatear porque no se ha configurado ningún tipo de datos válido.",
    fieldTypeRichTextNotAvailableLinkText: "Lea cómo configurar un tipo de datos.",
    addToTop: "Agregar página al inicio del formulario",
    addToBottom: "Agregar página al final del formulario",
    mandatoryFieldSetLegendMissingTitle: "Uno o más grupos no tienen un título completo",
    mandatoryFieldSetLegendMissingDescription: "Estos deben proporcionar un formulario accesible.",
    chooseFieldType: "Elija el tipo de campo",
    editField: "Editar campo",
    editSubmitMessage: "Editar enviar mensaje",
    editWorkflow: "Editar flujo de trabajo",
    jumpToPage: "Saltar a la págine",
    noNameForForm: "Por favor proporcione un nombre"
  },
  formFileUpload: {
    allowAllFiles: "Permitir todos los archivos",
    allowOnlySpecifiedFiles: "Permitir solo archivos específicos",
    predefinedAllowedFileTypes: "Tipos de archivos permitidos predefinidos",
    userDefinedAllowedFileTypes: "Tipos de archivos permitidos definidos por el usuario",
    deleteAllowedFileTypeConfirmationTitle: "Confirmación",
    deleteAllowedFileTypeConfirmationDescription: "¿Estás seguro/a de que quieres eliminar esto?",
    duplicateFileTypeErrorTitle: "Error del tipo de archivo",
    duplicateFileTypeErrorMessage: "No se puede agregar el tipo de archivo porque es un duplicado.",
    disallowedFileExtensionErrorTitle: "Tipo de archivo no permitido",
    disallowedFileExtensionErrorMessage: "Este tipo de archivo no se puede agregar porque su uso ha sido prohibido.",
    pickFile: "Seleccionar archivo",
    uploading: "Cargando",
    currentFile: "Archivo actual",
    addAllowedFileType: "Añadir un nuevo tipo de archivo permitido"
  },
  formPrevalues: {
    newValue: "Nuevo valor",
    newCaption: "Nuevo título",
    caption: "Título",
    duplicateErrorTitle: "Error de prevalor",
    duplicateAddErrorMessage: "No se puede agregar valor ya que crearía un duplicado.",
    duplicateEditErrorMessage: "No se puede agregar valor ya que crearía un duplicado.",
    deletePrevalueHeadline: "Eliminar prevalor",
    deletePrevalueMessage: "¿Está seguro de que desea eliminar este prevalor?"
  },
  formDelete: {
    modalHeadline: "Eliminar formulario",
    title: "¿Está seguro de que desea eliminar el formulario '%0%'?",
    timingNote: "Tenga en cuenta que esto puede llevar mucho tiempo dependiendo de la cantidad de registros.",
    recordDeleteNote: "Eliminar el formulario también eliminará los registros asociados.",
    noRecordDetail: "No hay entradas asociadas al formulario.",
    recordDetail: (e, a) => `Hay ${e} registros, y el más reciente se envió el ${a}.`,
    cannotDeleteFolder: "La carpeta seleccionada no se puede eliminar porque no está vacía.",
    successMessageForForm: "El formulario se eliminó correctamente.",
    failedMessageForForm: "El formulario no se pudo eliminar.",
    successMessageForFolder: "Se eliminó la carpeta con éxito.",
    failedMessageForFolder: "La carpeta no se pudo borrar.",
    deleteWarning: "Se hace referencia a este formulario en una o más páginas de contenido. La eliminación podría provocar que se interrumpa la funcionalidad de su sitio web.",
    noReferencedMessage: "Actualmente no se hace referencia al formulario en ninguna página de contenido.",
    folderDeleteModalHeadline: "Eliminar un formulario o una carpeta",
    folderDeleteConfirmationMessage: "¿Estás seguro de que deseas eliminar la carpeta '{0}'?",
    folderNotEmptyMessage: "Esta carpeta no se puede eliminar porque no está vacía."
  },
  formEntries: {
    title: (e) => `${e} Entradas`,
    filterEntries: "Filtrar entradas...",
    selectedRowsDescription: (e, a) => `${e} de ${a} seleccionados`,
    export: "Exportar",
    chooseExportFormat: "Elija un formato para exportar registros de formulario",
    entriesNotStored: "Actualmente, los envíos no se almacenan en la base de datos.",
    enableStoreEntries: 'Para habilitar esto, vaya a la configuración del formulario y active la función "Almacenar registros".',
    noEntriesInRange: "Aún no se agregaron presentaciones en este rango de fechas.",
    noEntriesInRangeDetail: "No pudimos encontrar ningún envío, ¿está seguro de que publicaste el formulario? O intenta ampliar el intervalo de fechas.",
    noEntriesMatchingSearch: "No pudimos encontrar ningún envío que coincida con tu búsqueda.",
    noEntriesMatchingSearchDetail: "Intente buscar otra cosa, tal vez tengas suerte la próxima vez.",
    selectedEntryPaging: (e, a) => `Entrada ${e} de ${a}`,
    previousEntry: "Entrada anterior",
    nextEntry: "Entrada siguiente",
    accessDeniedMessage: "No tienes acceso para ver las entradas de este formulario.",
    executeCompleteTitle: "Acción ejecutada",
    executeSuccessMessage: (e) => `Acción ejecutada con éxito ${e}`,
    executeErrorMessage: (e, a) => `FError al ejecutar la acción ${e} debido a error: ${a}.`,
    entryDetails: "Detalles de la entrada",
    closeDetails: "Cerrar detalles",
    submittedOn: "Enviado el",
    updatedOn: "Actualizado en",
    fromPage: "De la página",
    member: "Miembro",
    state: "Estado",
    uniqueId: "Identificación única",
    auditTrail: "Pista de auditoría",
    showAuditTrail: "Mostrar pista de auditoría",
    hideAuditTrail: "Ocultar pista de auditoría",
    updatedBy: "Actualizado por",
    updateRecordSuccess: "Registro actualizado",
    updateRecordError: "No se pudo actualizar el registro",
    workflowAudit: "Auditoría de flujo de trabajo",
    workflowAuditName: "Nombre",
    workflowAuditType: "Tipo",
    workflowAuditExecutedOn: "Ejecutado en",
    workflowAuditExecutionStage: "Fase",
    workflowAuditResult: "Resultado",
    workflowAuditTitleFormatSingular: (e, a) => `${e} de ${a} flujo de trabajo exitoso`,
    workflowAuditTitleFormatPlural: (e, a) => `${e} de ${a} flujos de trabajo exitosos`,
    workflowAuditRetry: "Rever",
    workflowAuditRunAgain: "Ejecutar de nuevo",
    workflowAuditRunAnyway: "Ejecutar de todos modos",
    workflowAuditRetryConfirmTitle: "Confirmación",
    workflowAuditRetryConfirmMessage: "¿Estás seguro de que deseas volver a ejecutar el flujo de trabajo seleccionado?",
    workflowAuditRetrySuccessMessage: "La ejecución del flujo de trabajo se completó (consulte la pista de auditoría para ver el estado y consulte los registros para un resultado no exitoso)",
    workflowAuditRetryFailedMessage: "La ejecución del flujo de trabajo falló",
    workflowAuditRetryFailedMessageDetailWorkflowNotFound: "El flujo de trabajo ya no está asociado con el formulario.",
    workflowExecutionStageSubmitted: "Presentada",
    workflowExecutionStageApproved: "Aprobada",
    workflowExecutionStageRejected: "Rechazada",
    workflowExecutionStatusCompleted: "Terminado",
    workflowExecutionStatusFailed: "Fallido",
    workflowExecutionStatusNotConfigured: "No configurado",
    workflowExecutionStatusCancelled: "Cancelado",
    workflowExecutionStatusSkippedDueToConditions: "Ignorado por condiciones",
    formSubmissionHeadline: "Envío de formulario",
    recordAudit: "Auditoría de registros",
    goToDocument: "Ir al documento",
    runWorkflow: "Ejecutar flujo de trabajo"
  },
  formMove: {
    moveButtonLabel: "Mover",
    formMoveModalHeadline: "Mover formulario",
    title: (e) => `Seleccione la carpeta a la que se moverá <strong>${e}</strong> en la estructura de árbol a continuación.`,
    successMessage: (e, a) => `<strong>${e}</strong> se movió debajo <strong>${a}</strong>.`,
    successNotificationHeader: "Movido",
    successNotificationDescriptionForForm: "El formulario se movió al lugar seleccionado.",
    successNotificationDescriptionForFolder: "El formulario se movió al lugar seleccionado.",
    folderMoveModalHeadline: "Mover carpeta"
  },
  formRename: {
    enterNewName: "Ingresa el nombre nuevo",
    successNotificationHeader: "Renombrado",
    successNotificationDescriptionForFolder: "La carpeta se renombró."
  },
  formConditions: {
    title: "Condiciones",
    enableConditions: "Activar condiciones",
    actionTypeShow: "Mostrar",
    actionTypeHide: "Ocultar",
    workflowactionTypeShow: "Ejecute",
    workflowactionTypeHide: "Ignorar",
    logicTypeAll: "todo",
    logicTypeAny: "alguno",
    operatorIs: "es",
    operatorIsNot: "no es",
    operatorGreaterThen: "es mayor que",
    operatorLessThen: "es menos que",
    operatorContains: "contiene (distingue entre mayúsculas y minúsculas)",
    operatorContainsIgnoreCase: "contiene (no distingue entre mayúsculas y minúsculas)",
    operatorStartsWith: "comienza con (distingue entre mayúsculas y minúsculas)",
    operatorStartsWithIgnoreCase: "comienza con (no distingue entre mayúsculas y minúsculas)",
    operatorEndsWith: "termina con (distingue entre mayúsculas y minúsculas)",
    operatorEndsWithIgnoreCase: "termina con (no distingue entre mayúsculas y minúsculas)",
    operatorNotContains: "no contiene (distingue entre mayúsculas y minúsculas)",
    operatorNotContainsIgnoreCase: "no contiene (no distingue entre mayúsculas y minúsculas)",
    operatorNotStartsWith: "no comienza con (distingue entre mayúsculas y minúsculas)",
    operatorNotStartsWithIgnoreCase: "no comienza con (no distingue entre mayúsculas y minúsculas)",
    operatorNotEndsWith: "no termina en (distingue entre mayúsculas y minúsculas)",
    operatorNotEndsWithIgnoreCase: "no termina con (no distingue entre mayúsculas y minúsculas)",
    thisFieldSetIf: "este conjunto de campos si",
    thisFieldIf: "este campo si",
    buttonsForThisPageIf: "botones para esta página si",
    thisWorkflowIf: "este flujo de trabajo si",
    ofTheFollowingMatch: "del siguiente partido",
    selectField: "Selecciona campo",
    addCondition: "Añadir condición",
    pageConditionsDescription: 'Opcionalmente, defina las condiciones para la visualización del botón "Enviar" o "Siguiente" para la página.',
    pageButtonConditionStatus: (e, a) => `${e} botones para esta página si <strong>${a}</strong> del siguiente partido:`,
    fieldsetConditionStatus: (e, a) => `${e} este grupo si <strong>${a}</strong> del siguiente partido:`,
    fieldConditionStatus: (e, a) => `${e} esta pregunta si <strong>${a}</strong> del siguiente partido:`,
    empty: "vacío"
  },
  formThemes: {
    noThemesAvailable: "No hay temas disponibles. Agregar temas a / Vistas / Parciales / Formularios / Temas"
  },
  formWorkflows: {
    workflowNameLabel: "El nombre del flujo de trabajo",
    workflowNameDescription: "Pon un nombre descriptivo a tu flujo de trabajo",
    workflowTypeLabel: "Tipo de flujo de trabajo",
    workflowTypeDescription: "El tipo de flujo de trabajo seleccionado",
    activeLabel: "Activo",
    activeDescription: "Habilita o deshabilita el flujo de trabajo",
    includeSensitiveDataLabel: "Incluye datos sensibles",
    includeSensitiveDataDescription: "¿Incluyes datos sensibles al ejecutar este flujo de trabajo?",
    submitMessage: "Enviar mensaje / Ir a la página",
    approve: "Aprobar",
    automatic: "automatico",
    noWorkflowsAdded: "No se agregan flujos de trabajo",
    configureWorkflow: "Configurar el flujo de trabajo",
    saveFailedTitle: "El flujo de trabajo no se pudo guardar",
    closeConfirmationTitle: "Confirmación",
    closeConfirmationMessage: "Se han realizado cambios que no se han guardado. ¿Estás seguro de que deseas cerrar?",
    chooseWorkflow: "Elija el flujo de trabajo",
    on: "Al",
    onSubmit: "Al enviar",
    onSubmitDescription: "Ejecutaremos estos flujos de trabajo cuando envíe el formulario.",
    onApprove: "Al aprobar",
    onApproveDescription: "Estos flujos de trabajo se ejecutarán cuando se apruebe la entrada.",
    onApproveAutomaticDescription: "esto sucede automáticamente después del evento de envío con la configuración actual del formulario",
    reject: "Rechazar",
    onReject: "Al rechazar",
    onRejectDescription: "Estos flujos de trabajo se ejecutarán cuando se rechace la entrada",
    defaultWorkflowName: "Enviar mensaje / Ir a la página",
    defaultWorkflowDescription: "Muestre un mensaje cuando se envíe el formulario o vaya a una página de Umbraco",
    addWorkflow: "Agregar flujo de trabajo",
    messageOnSubmit: "Mensaje al enviar",
    messageOnSubmitDescription: "Muestre un mensaje cuando se envía el formulario",
    messageFormat: "Formato de mensaje",
    messageOnSubmitIsHtmlToggleTextOn: "Dar formato al mensaje en texto enriquecido",
    messageOnSubmitIsHtmlToggleTextOff: "Dar formato al mensaje en texto sin formato",
    goToPage: "Ir a la pagina",
    goToPageDescription: "Accede a una página de Umbraco cuando se envía el formulario",
    chooseWorkflowType: "Elija el tipo de flujo de trabajo"
  },
  fieldSetColumns: {
    title: "Columnas",
    setNumber: "Establece cuántas columnas deseas tener en tu grupo.",
    columnNumberDescription: (e) => `Este grupo tiene actualmente ${e} columnas.`,
    addColumn: "Añadir columna"
  },
  fieldSettings: {
    namePlaceholder: "Ingrese una pregunta...",
    descriptionPlaceholder: "Ingrese el texto de ayuda...",
    requiredLabel: "Etiqueta obligatoria",
    chooseAnswerType: "Elige el tipo de respuesta",
    sensitiveData: "Datos sensibles",
    sensitiveDataDescription: "Evita que los datos sean visualizados y exportados si un usuario no tiene permisos suficientes.",
    sensitiveDataLabel: "Sí, este campo almacena datos confidenciales",
    allowedFileUploadTypes: "Tipos permitidos de carga de archivos",
    prevalues: "Opciones",
    prevaluesProvideWithSources: "Proporciona aquí una lista de opciones (prevalores) específicos para este campo o selecciona una fuente de prevalor predefinida.",
    prevaluesProvide: "Proporciona una lista de opciones (prevalores) para el campo.",
    prevaluesItems: "Elementos",
    prevaluesSource: "Fuente de prevalor",
    pressEnterToAdd: "Presiona el botón enter para agregar un valor",
    settings: "Configuraciones",
    mandatory: "Obligatorio",
    enterRegex: "Ingresa una expresión regular",
    invalidPlaceholder: "Ingresa un mensaje de campo inválido...",
    allowMultipleFileUploads: "Permitir múltiples cargas de archivos",
    multipleFilesToggleTextOn: "Se permiten varios archivos",
    multipleFilesToggleTextOff: "Solo archivo individual"
  },
  formSettings: {
    storeRecords: "Registros de la tienda",
    storeRecordsDescription: `
      Marque esta casilla para guardar los registros enviados en una base de datos.
      Esto te permitirá verlos y exportarlos desde la descripción general de las consultas.
      Si no quieres almacenar datos (debido a las políticas de tu organización), deja la casilla sin marcar.
    `,
    storeRecordsConfirm: "Sí, mantenga los registros enviados en una base de datos, para que se puedan ver y exportar más tarde.",
    captions: "Subtítulos",
    captionsDescription: "Cambia los títulos de los botones Enviar, Siguiente y Anterior.",
    captionSubmitButton: 'Etiqueta del botón "Enviar"',
    captionNextButton: "Etiqueta del botón 'Siguiente'",
    captionPreviousButton: 'Etiqueta del botón "Anterior"',
    styling: "Estilizar",
    stylingDescription: "Agrega una o más clases para ajustar tu formulario para habilitar el estilo personalizado, deshabilitar el estilo predeterminado y cargar activos con Dependencia del cliente.",
    formCssClass: "Formulario de clase CSS",
    disableDefaultStylesheet: "Desactivar hoja de estilo predeterminada",
    loadWithClientDependency: "Cargar activos con dependencia del cliente",
    validation: "Validación",
    validationDescription: "Proporcions mejores mensajes de validación, oculta las etiquetas de validación y cambie o deshabilite el marcador obligatorio.",
    mandatoryErrorMessage: "Mensaje de error obligatorio",
    mandatoryErrorMessageDescription: "Mensaje para mostrar cuando un campo obligatorio se deja vacío",
    invalidErrorMessage: "Mensaje de error no válido",
    invalidErrorMessageDescription: "Mensaje para mostrar cuando un campo no es válido",
    showValidationSummary: "Mostrar resumen de validación",
    hideFieldValidationLabels: "Ocultar etiquetas de validación de campo",
    markFields: "Marcar campos",
    markFieldsNoIndicator: "Sin indicador",
    markMandatoryFields: "Marcar campos obligatorios",
    markOptionalFields: "Marcar campos opcionales",
    indicator: "Indicator",
    changeIndicatorSymbol: "Cambiar el símbolo indicador obligatorio",
    autocomplete: "Autocompletar",
    autocompleteDescription: "Agregue un atributo para controlar el comportamiento general de autocompletar formularios.",
    autocompleteNone: "Ninguno",
    autocompleteOn: "Abierto",
    autocompleteOff: "Apagado",
    moderation: "Moderation",
    moderationDescription: "Permite que los envíos de formularios sean moderados antes de la publicacion. La mayoría de los casos de uso son para entradas que se muestran públicamente, como comentarios de publicaciones de blogs o presentaciones para una campaña social.",
    enablePostModeration: "Habilitar la moderación de publicaciones",
    deleteTitle: (e) => `Eliminar la seguridad del usuario: ${e}`,
    deleteUserRecordNote: "Al eliminar el registro de seguridad del usuario, los permisos del usuario se derivarán de los grupos de usuarios de los que son miembros..",
    deleteSuccessMessage: "Registro de seguridad del usuario eliminado.",
    deleteFailedMessage: "No se pudo eliminar el registro de seguridad del usuario.",
    fieldsDisplayed: "Campos mostrados",
    fieldsDisplayedDescription: "Seleccione qué campos se muestran en la lista de entradas del formulario.",
    displayDefaultFields: "Mostrar campos predeterminados",
    displayDefaultFieldsDescription: "De forma predeterminada, se muestran los valores proporcionados para los tres primeros campos del formulario, junto con algunos campos del sistema..",
    formFields: "Campos de formulario",
    systemFields: "Campos del sistema",
    noSelectedDisplayFields: "No se han seleccionado campos para mostrar.",
    resetDisplayDefaultFieldsMessage: "¿Está seguro de que desea volver a la selección de campo predeterminada para mostrar? Los campos personalizados que haya seleccionado se eliminarán cuando se guarde el formulario.",
    dataRetention: "Retención de datos",
    dataRetentionDescription: "Defina cuánto tiempo se guardan los envíos de formularios antes de que se eliminen automáticamente.",
    dataRetentionForSubmittedRecords: "Número de días para conservar los registros enviados",
    dataRetentionForApprovedRecords: "Número de días para conservar los registros aprobados",
    dataRetentionForRejectedRecords: "Número de días para conservar los registros rechazados",
    dataRetentionRetainSubmittedRecords: "Conservar los registros enviados para siempre",
    dataRetentionRetainApprovedRecords: "Conserve los registros aprobados para siempre",
    dataRetentionRetainRejectedRecords: "Conservar los registros rechazados para siempre",
    dataRetentionRemoveSubmittedRecords: "Eliminar registros enviados",
    dataRetentionRemoveApprovedRecords: "Eliminar registros aprobados",
    dataRetentionRemoveRejectedRecords: "Eliminar registros rechazados",
    scheduledRecordDeletionNotEnabled: "El servicio de eliminación de registros programados no se está ejecutando actualmente. Estos ajustes no tendrán efecto hasta que el servicio esté habilitado en la configuración.",
    referencesTitle: "Referenciado por los siguientes elementos",
    noReferencesTitle: "Este artículo no tiene referencias.",
    multiPageForms: "Formularios de varias páginas",
    multiPageFormsDescription: "Aplique la siguiente configuración a formularios de varias páginas",
    multiPageFormsShowPaging: "Pantalla de paginación",
    multiPageFormsShowSummaryPage: " Mostrar página de resumen",
    multiPageFormsNavigationNone: "Ninguna",
    multiPageFormsNavigationShowOnTop: "Mostrar en la parte superior",
    multiPageFormsNavigationShowOnBottom: "Mostrar en la parte inferior",
    multiPageFormsNavigationShowOnTopAndBottom: "Mostrar en la parte superior e inferior",
    pagingDetailsFormat: "Formato de visualización de paginación",
    pageCaptionFormat: "Formato de título de página",
    summaryLabel: "Título resumido"
  },
  formAdvanced: {
    validationRules: "Reglas de validación",
    validationRulesDescription: "Definiciones de reglas de validación de formularios aplicadas a dos o más campos.",
    validationRuleDefinition: "Definición de regla",
    validationRuleErrorMessage: "Mensaje de error",
    validationRulesRuleDescription: 'La definición de regla definida utilizando la <a href="https://jsonlogic.com/" target="_blank">sintaxis JsonLogic</a>. Los campos de formulario están referenciados por un alias rodeado por llaves, p. {myAliasForFormField}.',
    validationRulesErrorMessageDescription: "El mensaje de error de validación que se muestra al usuario que envía el formulario si no se cumple la definición de la regla.",
    validationRulesFieldDescription: "El campo en el que se mostrará el mensaje de error de validación.",
    validationRulesErrorTitle: "Regla no válida rule",
    validationRulesRuleErrorDescription: "No se pudo analizar la definición de la regla.",
    validationRulesMessageErrorDescription: "Por favor proporcione un mensaje de error.",
    validationRulesFieldErrorDescription: "Seleccione un campo para asociar el mensaje de error.",
    deleteValidationRuleHeadline: "Eliminar regla de validación",
    deleteValidationRuleMessage: "¿Estás seguro de que deseas eliminar esta regla de validación?"
  },
  formSecurity: {
    saveSuccessTitle: "Se guardó la seguridad del formulario de usuario",
    saveErrorTitle: "No se pudo guardar la seguridad del formulario de usuario",
    manageFormsLabel: "Gestionar formularios",
    manageFormsDescription: "Otorgar o denegar el acceso a los formularios de gestión.",
    manageWorkflowsLabel: "Gestionar los flujos de trabajo",
    manageWorkflowsDescription: "Otorgar o denegar acceso para administrar todos los elementos del flujo de trabajo de formularios",
    manageDatasourcesLabel: "Gestionar fuentes de datos.",
    manageDatasourcesDescription: "Otorgar o denegar el acceso a la administración de cualquier fuente de datos para todos los formularios.",
    managePrevalueSourcesLabel: "Gestionar fuentes de prevalorización",
    managePrevalueSourcesDescription: "Otorgar o denegar el acceso a la gestión de fuentes de prevalor para todos los formularios.",
    manageIndividualFormsLabel: "Seguridad del formulario",
    manageIndividualFormsDescription: "Otorgar o denegar el acceso a formularios individuales",
    startFolders: "Carpetas de inicio",
    startFoldersDescription: "Defina la carpeta o carpetas raíz para el usuario",
    selectNewStartFolders: "Seleccionar carpetas de inicio",
    formName: "Nombre del formulario",
    hasAccess: "Tiene acceso",
    viewEntriesLabel: "Ver entradas",
    viewEntriesDescription: "Otorgar o denegar el acceso para ver las entradas enviadas",
    editEntriesLabel: "Editar entradas",
    editEntriesDescription: "Otorgar o denegar el acceso a la edición de las entradas enviadas",
    deleteEntriesLabel: "Eliminar entradas",
    deleteEntriesDescription: "Otorgar o denegar el acceso para eliminar las entradas enviadas",
    createTitle: "Crear seguridad de usuario",
    createUserRecordNote: "Cuando se crea un registro de usuario, tendrá prioridad sobre cualquier permiso asignado a nivel de grupo de usuarios..",
    selectUser: "Seleccionar usuario",
    allUsersHaveRecords: "Todos los usuarios ya tienen registros de seguridad creados.",
    groupPermissions: "Permisos de grupo",
    userPermissions: "Permisos de usuario",
    selectAndDeselect: "Seleccionar/Deseleccionar todo",
    deleteTitle: (e) => `Eliminar seguridad del usuario: ${e}`,
    packagePermissions: "Permisos de paquetes"
  },
  formDataSources: {
    typeDescription: "Seleccione el tipo de fuente de datos",
    createForm: "Crear formulario",
    formName: "Nombre del formulario",
    selectFields: "Seleccione campos",
    selectFieldsDescription: "Campos de la fuente de datos que desea incluir en el formulario.",
    setupForeignKeys: "Configurar claves foráneas",
    setupForeignKeysDescription: "Seleccione la columna de valor para los campos de clave externa.",
    selectType: "Seleccione tipo",
    selectTypeDescription: "Tipo de campo que deseas utilizar para los campos incluidos (o valor predeterminado).",
    defaultValue: "Valor predeterminado",
    deleteConfirm: (e) => `¿Estás seguro de que deseas eliminar la fuente de datos ${e}?`,
    saveSuccessTitle: "Se guardó la fuente de datos",
    saveErrorTitle: "No se pudo guardar la fuente de datos",
    accessDeniedMessage: "No tienes acceso para editar fuentes de datos",
    createFormFromDataSource: "Crear formulario desde fuente de datos",
    chooseDatasourceType: "Elija el tipo de fuente de datos",
    deleteDatasource: "Eliminar fuente de datos"
  },
  formPrevalueSources: {
    typeDescription: "Seleccione el tipo de fuente de prevalor",
    deleteConfirm: (e) => `¿Estás seguro/a de que quieres eliminar la fuente de prevalencia '${e}'?`,
    saveSuccessTitle: "Se guardó la fuente de la prevaluación",
    saveErrorTitle: "No se pudo guardar la fuente de la prevaluación",
    accessDeniedMessage: "No tienes acceso para editar fuentes de prevalor",
    cacheOptionsLabel: "Opciones de caché",
    cacheOptionsDescription: "Elija cómo almacenar en caché la lista de valores previos al representar en un formulario.",
    cacheOptionsNone: "Sin almacenamiento en caché",
    cacheOptionsTime: "Caché por tiempo especificado",
    cacheOptionsNoExpiry: "Caché sin caducidad",
    cacheOptionsEnterTime: "Prevalores de caché para",
    cacheOptionsSeconds: "segundos",
    cacheOptionsMinutes: "minutos",
    cacheOptionsHours: "horas",
    deleteSuccessMessage: "El fuente de prevalor se eliminó correctamente.",
    deleteFailedMessage: "El fuente de prevalor no se pudo eliminar.",
    choosePrevalueSourceType: "Elija el tipo de fuente de valor previo",
    deletePrevalueSource: "Eliminar fuente de valor previo",
    designModalHeadline: "Detalles",
    listHeadline: "Lista de valores previos"
  },
  formPropertyEditors: {
    standardFields: "Campos estándar",
    customFields: "Campos personalizados"
  },
  formProviderFieldTypes: {
    checkboxName: "Casilla de verificación",
    checkboxDescription: "Muestra una casilla de verificación.",
    checkboxCaptionValueLabel: "Subtítulo",
    checkboxCaptionValueDescription: "El texto asociado con la casilla de verificación.",
    checkboxDefaultValueLabel: "Valor predeterminado",
    checkboxDefaultValueDescription: "Ingrese un valor predeterminado.",
    multipleChoiceName: "Opción multiple",
    multipleChoiceDescription: "Muestra una colección de casillas de verificación para seleccionar varias respuestas.",
    multipleChoiceDisplayLayoutLabel: "Diseño de pantalla",
    multipleChoiceDisplayLayoutDescription: "Indique si el diseño del campo debe ser horizontal o vertical (valor predeterminado si no se especifica).",
    multipleChoiceDefaultValueLabel: "Valor predeterminado",
    multipleChoiceDefaultValueDescription: "Ingrese un valor predeterminado.",
    multipleChoiceShowLabelLabel: "Mostrar etiqueta",
    multipleChoiceShowLabelDescription: "Indique si la etiqueta del campo debe mostrarse al renderizar el formulario.",
    dataConsentName: "Consentimiento para los datos",
    dataConsentDescription: "Genera un campo para solicitar el consentimiento de los datos.",
    dataConsentAcceptCopyLabel: "Aceptar copia",
    dataConsentAcceptCopyDescription: "El texto utilizado para confirmar el consentimiento.",
    dataConsentShowLabelLabel: "Mostrar etiqueta",
    dataConsentShowLabelDescription: "Indique si la etiqueta del campo debe mostrarse al renderizar el formulario.",
    dateName: "Fecha",
    dateDescription: "Genera un selector de fechas.",
    datePlaceholderLabel: "Placeholder",
    datePlaceholderDescription: "Ingrese un valor para el placeholder.",
    dateShowLabelLabel: "Mostrar etiqueta",
    dateShowLabelDescription: "Indique si la etiqueta del campo debe mostrarse al renderizar el formulario.",
    dateAriaLabelLabel: "Etiqueta de tecnología de asistencia",
    dateAriaLabelDescription: "Ingrese una descripción de cómo seleccionar una fecha, utilizada por tecnologías de asistencia como lectores de pantalla.",
    dropdownName: "Menú desplegable",
    dropdownDescription: "Muestra una lista de valores en un menú desplegable",
    dropdownDefaultValueLabel: "Valor predeterminado",
    dropdownDefaultValueDescription: "Ingrese un valor predeterminado.",
    dropdownAllowMultipleSelectionsLabel: "Permitir selecciones múltiples",
    dropdownAllowMultipleSelectionsDescription: "Indique si se permiten múltiples selecciones de la lista.",
    dropdownShowLabelLabel: "Mostrar etiqueta",
    dropdownShowLabelDescription: "Indique si la etiqueta del campo debe mostrarse al renderizar el formulario.",
    dropdownAutocompleteAttributeLabel: "Atributo de autocompletar",
    dropdownAutocompleteAttributeDescription: "Opcionalmente, ingrese un valor para el atributo de autocompletar.",
    dropdownSelectPromptLabel: "Solicitud de selección",
    dropdownSelectPromptDescription: "Opcionalmente, proporcione un aviso para la selección del usuario..",
    fileUploadName: "Subir archivo",
    fileUploadDescription: "Representa un campo de carga, lo que permite cargar archivos.",
    fileUploadSelectedFilesListHeadingLabel: "Encabezado de lista de archivos seleccionados",
    fileUploadSelectedFilesListHeadingDescription: "El encabezado utilizado para la lista de archivos seleccionados para cargar en formularios de varias páginas.",
    fileUploadShowLabelLabel: "Mostrar etiqueta",
    fileUploadShowLabelDescription: "Indique si la etiqueta del campo debe mostrarse al renderizar el formulario.",
    fileUploadErrorMessageForMultipleFileUploadLabel: "Mensaje de error (varias cargas de archivos)",
    fileUploadErrorMessageForMultipleFileUploadDescription: "El mensaje de error que se mostrará si se carga más de un archivo cuando solo se configuran archivos individuales. Déjelo vacío para usar un mensaje predeterminado en inglés.",
    fileUploadErrorMessageForInvalidFileExtensionLabel: "Mensaje de error (la extensión no coincide)",
    fileUploadErrorMessageForInvalidFileExtensionDescription: "El mensaje de error que se mostrará si se carga un archivo con una extensión que no coincide con la lista permitida. Déjelo vacío para usar un mensaje predeterminado en inglés.",
    fileUploadErrorMessageForMissingFileExtensionLabel: "Mensaje de error (falta la extensión)",
    fileUploadErrorMessageForMissingFileExtensionDescription: "El mensaje de error que se mostrará si se carga un archivo sin extensión. Déjelo vacío para usar un mensaje predeterminado en inglés",
    fileUploadErrorMessageForInvalidCharacterInFileNameLabel: "Mensaje de error (carácter no válido en el nombre del archivo)",
    fileUploadErrorMessageForInvalidCharacterInFileNameDescription: "El mensaje de error que se mostrará si se carga un archivo con un carácter no válido en su nombre. Déjelo vacío para usar un mensaje predeterminado en inglés.",
    fileUploadErrorMessageForFailedSecurityCheckLabel: "Mensaje de error (verificación de seguridad fallida)",
    fileUploadErrorMessageForFailedSecurityCheckDescription: "El mensaje de error que se mostrará si se carga un archivo que no pasa la verificación de seguridad. Déjelo vacío para usar un mensaje predeterminado en inglés.",
    hiddenName: "Oculto",
    hiddenDescription: "Genera un campo oculto.",
    hiddenDefaultValueLabel: "Valor predeterminado",
    hiddenDefaultValueDescription: "Ingrese un valor predeterminado.",
    passwordName: "Contraseña",
    passwordDescription: "Muestra un campo de contraseña.",
    passwordPlaceholderLabel: "Placeholder",
    passwordPlaceholderDescription: "Ingrese un valor para el campo (placeholder).",
    singleChoiceName: "Elección única",
    singleChoiceDescription: "Muestra una lista de botones de opción para habilitar una respuesta de opción única.",
    singleChoiceDefaultValueLabel: "Valor predeterminado",
    singleChoiceDefaultValueDescription: "Ingrese un valor predeterminado.",
    singleChoiceShowLabelLabel: "Mostrar etiqueta",
    singleChoiceShowLabelDescription: "Indique si se debe mostrar la etiqueta del campo al procesar el formulario.",
    singleChoiceDisplayLayoutLabel: "Diseño de pantalla",
    singleChoiceDisplayLayoutDescription: "Indique si el diseño del campo debe ser horizontal o vertical (valor predeterminado si no se especifica).",
    recaptcha2Name: "reCAPTCHA v2",
    recaptcha2Description: "Google reCAPTCHA v2.",
    recaptcha2ThemeLabel: "Tema",
    recaptcha2ThemeDescription: "reCAPTCHA v2 theme.",
    recaptcha2SizeLabel: "Talla",
    recaptcha2SizeDescription: "reCAPTCHA v2 talla.",
    recaptcha2ErrorMessageLabel: "Mensaje de error",
    recaptcha2ErrorMessageDescription: "El mensaje de error que se muestra cuando el usuario no pasa la verificación reCAPTCHA.",
    recaptcha2ShowLabelLabel: "Mostrar etiqueta",
    recaptcha2ShowLabelDescription: "Indique si se debe mostrar la etiqueta del campo al procesar el formulario.",
    reCAPTCHAV3WithScoreName: "reCAPTCHA v3 con puntaje",
    reCAPTCHAV3WithScoreDescription: "Google reCAPTCHA v3 con umbral de puntuación",
    reCAPTCHAV3WithScoreScoreThresholdLabel: "Umbral de puntuación",
    reCAPTCHAV3WithScoreScoreThresholdDescription: "Una puntuación determinada de reCAPTCHA v3 entre 0 y 1, por encima del cual se aceptan envíos de formularios. Un valor más alto detectará más envíos de spam, pero también aumentará el riesgo de rechazo de entradas válidas. Para la mayoría de los sitios, 0.5 es una opción sensata..",
    reCAPTCHAV3WithScoreScoreErrorMessageLabel: "Mensaje de error",
    reCAPTCHAV3WithScoreScoreErrorMessageDescription: "El mensaje de error que se muestra cuando el usuario no pasa la verificación reCAPTCHA.",
    reCAPTCHAV3WithScoreScoreSaveScoreLabel: "Guardar puntuación",
    reCAPTCHAV3WithScoreScoreSaveScoreDescription: "Guarde la puntuación calculada con el envío del formulario.",
    richTextName: "Texto rico",
    richTextDescription: "Proporcione un poco de texto descriptivo con formato.",
    richTextHtmlLabel: "Texto rico",
    richTextHtmlDescription: "Ingrese su texto formateado",
    richTextShowLabelLabel: "Mostrar etiqueta",
    richTextShowLabelDescription: "Indique si se debe mostrar la etiqueta del campo al procesar el formulario.",
    titleAndDescriptionName: "Título y descripción",
    titleAndDescriptionDescription: "Esto se usa para ingresar texto descriptivo.",
    titleAndDescriptionCaptionLabel: "Título",
    titleAndDescriptionCaptionDescription: "Ingrese un título.",
    titleAndDescriptionBodyTextLabel: "Texto",
    titleAndDescriptionBodyTextDescription: "Ingrese el texto copiado.",
    titleAndDescriptionCaptionTagLabel: "Título del elemento HTML",
    titleAndDescriptionCaptionTagDescription: "Seleccione el elemento HTML que se usará al representar el título.",
    titleAndDescriptionShowLabelLabel: "Mostrar etiqueta",
    titleAndDescriptionShowLabelDescription: "Indique si debe mostrarse la etiqueta del campo al renderizar el formulario.",
    longAnswerName: "Respuesta larga",
    longAnswerDescription: "Genera un área de texto, diseñada para respuestas más largas.",
    longAnswerDefaultValueLabel: "Valor predeterminado",
    longAnswerDefaultValueDescription: "Ingrese un valor predeterminado.",
    longAnswerPlaceholderLabel: "Placeholder",
    longAnswerPlaceholderDescription: "Ingrese un valor para el placeholder.",
    longAnswerShowLabelLabel: "Mostrar etiqueta",
    longAnswerShowLabelDescription: "Indique si debe mostrarse la etiqueta del campo al renderizar el formulario.",
    longAnswerAutocompleteAttributeLabel: "Atributo de autocompletar",
    longAnswerAutocompleteAttributeDescription: "Opcionalmente, ingrese un valor para el atributo de autocompletar.",
    longAnswerNumberOfRowsLabel: "Número de filas",
    longAnswerNumberOfRowsDescription: "Ingrese el número de filas que se muestran para la entrada.",
    longAnswerMaximumLengthLabel: "Longitud máxima",
    longAnswerMaximumLengthDescription: "Ingrese el número máximo de caracteres aceptados.",
    shortAnswerName: "Respuesta corta",
    shortAnswerDescription: "Reproduce un campo de entrada de texto para respuestas breves.",
    shortAnswerDefaultValueLabel: "Valor predeterminado",
    shortAnswerDefaultValueDescription: "Ingrese un valor predeterminado.",
    shortAnswerPlaceholderLabel: "Placeholder",
    shortAnswerPlaceholderDescription: "Ingrese un valor para el placeholder.",
    shortAnswerShowLabelLabel: "Mostrar etiqueta",
    shortAnswerShowLabelDescription: "Indique si debe mostrarse la etiqueta del campo al renderizar el formulario.",
    shortAnswerMaximumLengthLabel: "Longitud máxima",
    shortAnswerMaximumLengthDescription: "Ingrese el número máximo de caracteres aceptados.",
    shortAnswerFieldTypeLabel: "Tipo de campo",
    shortAnswerFieldTypeDescription: "Seleccione el tipo de información esperada.",
    shortAnswerAutocompleteAttributeLabel: "Atributo de autocompletar",
    shortAnswerAutocompleteAttributeDescription: "Opcionalmente, ingrese un valor para el atributo de autocompletar."
  },
  formProviderWorkflows: {
    changeRecordStateName: "Cambiar estado de registro",
    changeRecordStateDescription: "Cambia el estado del registro que se está procesando cuando coincide con una palabra.",
    changeRecordStateWordsLabel: "Palabras",
    changeRecordStateWordsDescription: "Lista de palabras separadas por comas que deben coincidir.",
    changeRecordStateActionLabel: "Acción",
    changeRecordStateActionDescription: "Qué hacer si coincide.",
    postAsXmlName: "Publicar como XML",
    postAsXmlDescription: "Publica el formulario como XML en una URL.",
    postAsXmlUrlLabel: "URL",
    postAsXmlUrlDescription: "Ingrese la URL para publicar.",
    postAsXmlMethodLabel: "Método",
    postAsXmlMethodDescription: "POST o GET.",
    postAsXmlXsltFileLabel: "Archivo XSLT",
    postAsXmlXsltFileDescription: "Transforma el XML antes de publicarlo.",
    postAsXmlFieldsLabel: "Los campos",
    postAsXmlFieldsDescription: "Mapee los campos necesarios.",
    postAsXMLDefaultElementForFieldsLabel: "Elemento predeterminado para campos",
    postAsXMLDefaultElementForFieldsDescription: "Cuando no se asignan campos específicamente, todos los campos se proporcionan en la solicitud, utilizando el atributo del campo seleccionado como nombre del elemento. 'Caption' se utiliza de forma predeterminada.",
    postAsXmlUsernameLabel: "Usuario",
    postAsXmlUsernameDescription: "(opcional)",
    postAsXmlPasswordLabel: "Contraseña",
    postAsXmlPasswordDescription: "(opcional)",
    sendFormToURLName: "Enviar formulario a URL",
    sendFormToURLDescription: "Envía el formulario a una URL, ya sea como HTTP POST o GET.",
    sendFormToURLUrlLabel: "URL",
    sendFormToURLUrlDescription: "Ingrese la URL para publicar.",
    sendFormToURLMethodLabel: "Método",
    sendFormToURLMethodDescription: "POST o GET.",
    sendFormToURLStandardFieldsLabel: "Campos estándar",
    sendFormToURLStandardFieldsDescription: "Selecciona cualquier información de formulario estándar para enviar.",
    sendFormToURLFieldsLabel: "Campos",
    sendFormToURLFieldsDescription: "Seleccione los campos que necesitas",
    sendFormToURLDefaultElementForFieldsLabel: "Elemento predeterminado para campos",
    sendFormToURLDefaultElementForFieldsDescription: "Cuando no se asignan campos específicamente, todos los campos se proporcionan en la solicitud, utilizando el atributo del campo seleccionado como nombre del elemento. 'Caption' se utiliza de forma predeterminada.",
    sendFormToURLUsernameLabel: "Usuario",
    sendFormToURLUsernameDescription: "(opcional)",
    sendFormToURLPasswordLabel: "Contraseña",
    sendFormToURLPasswordDescription: "(opcional)",
    saveAsAnXmlFileName: "Guardar como archivo XML",
    saveAsAnXmlFileDescription: "Guarda el resultado del formulario como un archivo XML a través de XSLT.",
    saveAsAnXmlFilePathLabel: "Ruta",
    saveAsAnXmlFilePathDescription: "Ruta para colocar el archivo.",
    saveAsAnXmlFileExtensionLabel: "Extensión",
    saveAsAnXmlFileExtensionDescription: "Extensión de archivo.",
    saveAsAnXmlFileXsltFileLabel: "Archivo XSLT",
    saveAsAnXmlFileXsltFileDescription: "Transforma el XML antes de guardarlo.",
    saveAsUmbracoContentNodeName: "Guardar como Umbraco content node",
    saveAsUmbracoContentNodeDescription: "Guarda los valores del formulario como un nodo de contenido utilizando un tipo de documento especificado.",
    saveAsUmbracoContentNodeFieldsLabel: "Tipo de Documento",
    saveAsUmbracoContentNodeFieldsDescription: "Seleccione el tipo de documento.",
    saveAsUmbracoContentNodePublishLabel: "Publicar",
    saveAsUmbracoContentNodePublishDescription: "Publique el nodo al instante.",
    saveAsUmbracoContentNodeRootNodeLabel: "Guardar ubicación",
    saveAsUmbracoContentNodeRootNodeDescription: "Elija la ubicación donde guardar el nodo de contenido creado.",
    sendEmailName: "Enviar correo electrónico",
    sendEmailDescription: "Envíe el resultado del formulario a una dirección de correo electrónico.",
    sendEmailEmailLabel: "Receptor de E-mail",
    sendEmailEmailDescription: "Ingrese el correo electrónico del destinatario.",
    sendEmailCcEmailLabel: "CC Email",
    sendEmailCcEmailDescription: "Ingrese las direcciones de correo electrónico CC (si es necesario).",
    sendEmailBccEmailLabel: "BCC Email",
    sendEmailBccEmailDescription: "Ingrese las direcciones de correo electrónico BCC (si es necesario).",
    sendEmailSenderEmailLabel: "Correo electrónico del remitente",
    sendEmailSenderEmailDescription: "Ingresa el correo electrónico del remitente (si está en blanco, usará la configuración de configuración).",
    sendEmailReplyToEmailLabel: "Responder a un correo electrónico",
    sendEmailReplyToEmailDescription: "Ingresa la dirección de correo electrónico que se utilizará como dirección de respuesta (si es necesario).",
    sendEmailSubjectLabel: "Asunto",
    sendEmailSubjectDescription: "Ingrese el asunto.",
    sendEmailMessageLabel: "Mensaje",
    sendEmailMessageDescription: "Ingrese el mensaje introductorio.",
    sendEmailAttachmentLabel: "Archivos adjuntos",
    sendEmailAttachmentDescription: "Adjunte los archivos cargados al correo electrónico",
    sendEmailWithRazorTemplateName: "Enviar correo electrónico con plantilla (Razor)",
    sendEmailWithRazorTemplateDescription: "Envíe el resultado del formulario a una dirección / direcciones de correo electrónico utilizando una plantilla .cshtml de Razor.",
    sendEmailWithRazorTemplateEmailLabel: "Correo electrónico del destinatario",
    sendEmailWithRazorTemplateEmailDescription: "Ingrese la dirección/direcciones de correo electrónico del destinatario.",
    sendEmailWithRazorTemplateCcEmailLabel: "CC Email",
    sendEmailWithRazorTemplateCcEmailDescription: "Ingrese las direcciones de correo electrónico CC (si es necesario).",
    sendEmailWithRazorTemplateBccEmailLabel: "BCC Email",
    sendEmailWithRazorTemplateBccEmailDescription: "Ingrese las direcciones de correo electrónico BCC (si es necesario).",
    sendEmailWithRazorTemplateSenderEmailLabel: "Correo electrónico del remitente",
    sendEmailWithRazorTemplateSenderEmailDescription: "Ingrese el correo electrónico del remitente (si está en blanco, usará la configuración de configuración).",
    sendEmailWithRazorTemplateReplyToEmailLabel: "Responder a un correo electrónico",
    sendEmailWithRazorTemplateReplyToEmailDescription: "Ingrese la dirección de correo electrónico que se utilizará como dirección de respuesta (si es necesario).",
    sendEmailWithRazorTemplateSubjectLabel: "Asunto",
    sendEmailWithRazorTemplateSubjectDescription: "Ingrese el asunto.",
    sendEmailWithRazorTemplateRazorViewFilePathLabel: "Plantilla de correo electrónico",
    sendEmailWithRazorTemplateRazorViewFilePathDescription: "La ruta a la vista de Razor que desea usar para generar el correo electrónico. Las plantillas de correo electrónico se almacenan en /Views/Partials/Forms/Emails.",
    sendEmailWithRazorTemplateHeaderHtmlLabel: "Texto de encabezado con formato",
    sendEmailWithRazorTemplateHeaderHtmlDescription: "Ingrese el texto formateado que se representará en el encabezado del correo electrónico.",
    sendEmailWithRazorTemplateBodyHtmlLabel: "Texto del cuerpo formateado",
    sendEmailWithRazorTemplateBodyHtmlDescription: "Ingrese el texto formateado que se mostrará en el cuerpo del correo electrónico.",
    sendEmailWithRazorTemplateFooterHtmlLabel: "Texto de pie de página con formato",
    sendEmailWithRazorTemplateFooterHtmlDescription: "Ingrese el texto con formato que se representará en el pie de página del correo electrónico.",
    sendEmailWithRazorTemplateAttachmentLabel: "Adjuntos",
    sendEmailWithRazorTemplateAttachmentDescription: "Adjunte los archivos cargados al correo electrónico.",
    sendEmailWithXsltTemplateName: "Enviar correo electrónico transformado XSLT",
    sendEmailWithXsltTemplateDescription: "Envíe el resultado del formulario a una dirección de correo electrónico.",
    sendEmailWithXsltTemplateEmailLabel: "Correo electrónico del destinatario",
    sendEmailWithXsltTemplateEmailDescription: "Ingrese la dirección/direcciones de correo electrónico del destinatario.",
    sendEmailWithXsltTemplateCcEmailLabel: "CC Email",
    sendEmailWithXsltTemplateCcEmailDescription: "Ingrese las direcciones de correo electrónico CC (si es necesario).",
    sendEmailWithXsltTemplateBccEmailLabel: "BCC Email",
    sendEmailWithXsltTemplateBccEmailDescription: "Ingrese las direcciones de correo electrónico BCC (si es necesario).",
    sendEmailWithXsltTemplateSenderEmailLabel: "Correo electrónico del remitente",
    sendEmailWithXsltTemplateSenderEmailDescription: "Ingrese el correo electrónico del remitente (si está en blanco, usará la configuración de configuración).",
    sendEmailWithXsltTemplateReplyToEmailLabel: "Responder a un correo electrónico",
    sendEmailWithXsltTemplateReplyToEmailDescription: "Ingrese la dirección de correo electrónico que se usará como dirección de respuesta (si es necesario).",
    sendEmailWithXsltTemplateSubjectLabel: "Asunto",
    sendEmailWithXsltTemplateSubjectDescription: "Ingrese el asunto.",
    sendEmailWithXsltTemplateXsltFileLabel: "Archivo XSLT",
    sendEmailWithXsltTemplateXsltFileDescription: "Transforma el XML antes de enviar el correo electrónico.",
    slackLegacyName: "Slack (Legacy)",
    slackLegacyDescription: "Publica los datos del formulario en un canal específico en Slack utilizando tokens heredados.",
    slackLegacyTokenLabel: "API Token",
    slackLegacyTokenDescription: "Slack API token.",
    slackLegacyChannelLabel: "Channel",
    slackLegacyChannelDescription: "Slack channel para publicar.",
    slackLegacyUsernameLabel: "Nombre de usuario",
    slackLegacyUsernameDescription: "El nombre de usuario o bot con el que publicar.",
    slackLegacyAvatarUrlLabel: "Avatar URL",
    slackLegacyAvatarUrlDescription: "La URL completa (incluido http / https) de la imagen del avatar.",
    slackName: "Slack",
    slackDescription: "Publica los datos del formulario en un canal específico de Slack mediante un webhook.",
    slackWebhookUrlLabel: "URL del webhook",
    slackWebhookUrlDescription: "Slack Webhook URL."
  },
  formProviderDataSources: {
    sQLDatabaseName: "Base de datos SQL",
    sQLDatabaseDescription: "Se conecta a cualquier tabla de base de datos compatible con OLEDB y crea una fuente de datos a partir de ella.",
    sQLDatabaseConnectionLabel: "Connection String",
    sQLDatabaseConnectionDescription: "OleDB Compatible Connection string.",
    sQLDatabaseTableLabel: "Nombre de la tabla",
    sQLDatabaseTableDescription: "Nombre de la tabla de la base de datos."
  },
  formProviderPrevalueSources: {
    dataSourceName: "Fuente de datos",
    dataSourceDescription: "Almacena los prevalores en la tabla de prevalencia.",
    getValuesFromTextfileName: "Obtener valores del archivo de texto",
    getValuesFromTextfileDescription: "Cargue el archivo de texto que contiene los prevalores.",
    getValuesFromTextfileTextFileLabel: "Archivo de texto",
    getValuesFromTextfileTextFileDescription: "El archivo que contiene los valores previos (separados por saltos de línea).",
    umbracoDocumentsName: "Umbraco Documents",
    umbracoDocumentsDescription: "Utiliza nodos de una fuente específica como prevalores.",
    umbracoDocumentsRootNodeLabel: "Root node",
    umbracoDocumentsRootNodeDescription: "Fuente de la que se obtienen los nodos.",
    umbracoDocumentsUseCurrentPageLabel: "Usar la página actual como raíz",
    umbracoDocumentsUseCurrentPageDescription: "No funciona en modo de vista previa.",
    umbracoDocumentsDocTypeLabel: "Tipo de Documento",
    umbracoDocumentsDocTypeDescription: "El tipo de nodos que te gustaría usar.",
    umbracoDocumentsValueFieldLabel: "Campo de valor",
    umbracoDocumentsValueFieldDescription: "Seleccione qué campo debe usarse para el valor del prevalor.",
    umbracoDocumentsCaptionFieldLabel: "Campo de título",
    umbracoDocumentsCaptionFieldDescription: "Seleccione qué campo debe usarse para el título del valor previo.",
    umbracoDocumentsListGrandChildrenLabel: "La lista de todos los descendientes",
    umbracoDocumentsListGrandChildrenDescription: "No se limite a los niños, sino que también incluya otros niveles.",
    umbracoDocumentsOrderByLabel: "Ordenar por",
    umbracoDocumentsOrderByDescription: "Seleccione cómo se debe ordenar la lista de prevalores.",
    sQLDatabaseName: "Base de datos SQL",
    sQLDatabaseDescription: "Se conecta a una tabla de base de datos compatible con OLEDB y construye una fuente de prevalor a partir de ella.",
    sQLDatabaseConnectionLabel: "Connection String",
    sQLDatabaseConnectionDescription: "Connection String.",
    sQLDatabaseConnectionStringLabel: "Connection String de web.config",
    sQLDatabaseConnectionStringDescription: "Elija la cadena de conexión.",
    sQLDatabaseTableLabel: "Nombre de la tabla",
    sQLDatabaseTableDescription: "",
    sQLDatabaseKeyColumnLabel: "Columna clave",
    sQLDatabaseKeyColumnDescription: "Columna que contiene las claves.",
    sQLDatabaseValueColumnLabel: "Columna de valor",
    sQLDatabaseValueColumnDescription: "La columna que contiene los valores.",
    sQLDatabaseCaptionColumnLabel: "Columna de subtítulo",
    sQLDatabaseCaptionColumnDescription: "La columna que contiene los subtítulos.",
    umbracoDataTypePreValueName: "Umbraco data type PreValues",
    umbracoDataTypePreValueDescription: "Se conecta a un tipo de datos de Umbraco y usa su colección de prevalor.",
    umbracoDataTypePreValuesDataTypeIdLabel: "Tipo de datos",
    umbracoDataTypePreValuesDataTypeIdDescription: "Tipo de datos que se utilizarán."
  },
  formProviderExportTypes: {
    excelFileName: "Archivo Excel (valores enviados)",
    excelFileDescription: "Exporta todos los valores enviados para el formulario a Excel, en un formato útil para la integración con otros sistemas.",
    excelFileDisplayValuesName: "Archivo Excel (valores para mostrar)",
    excelFileDisplayValuesDescription: "Exporta todos los valores del formulario a Excel, en un formato útil para revisar los datos o crear un informe. Los subtítulos se utilizan para datos de valor previo cuando están disponibles.",
    excelFileNameOsx: "Archivo Excel/Numbers (valores enviados)",
    excelFileDescriptionOsx: "Exporta todos los valores enviados para el formulario a Excel/Numbers, en un formato útil para la integración con otros sistemas.",
    excelFileDisplayValuesNameOsx: "Archivo Excel/Numbers (valores para mostrar)",
    excelFileDisplayValuesDescriptionOsx: "Exporta todos los valores del formulario a Excel/Numbers, en un formato útil para revisar los datos o crear un informe. Los subtítulos se utilizan para datos de valor previo cuando están disponibles.",
    saveAllUploadedFilesInDiskStructureName: "Guardar todos los archivos cargados (en la estructura del disco)",
    saveAllUploadedFilesInDiskStructureDescription: "Exporta todos los archivos que se cargan en forma de envíos a un archivo zip, organizado a medida que los archivos se almacenan en el disco.",
    saveAllUploadedFilesByEntryName: "Guardar todos los archivos cargados (por entrada)",
    saveAllUploadedFilesByEntryDescription: "Exporta todos los archivos que se cargan en formularios enviados a un archivo zip, organizado en una subcarpeta por entrada."
  },
  formRecordSetActions: {
    deleteConfirm: "¿Está seguro/a de que desea eliminar estas entradas?"
  }
};
export {
  o as default
};
//# sourceMappingURL=es-es.js.map
