<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Copy packaged backoffice assets into the consuming Umbraco application's App_Plugins folder. -->
  <PropertyGroup>
    <SplatDevUmbracoPluginsPdfCuratorContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\**\*.*</SplatDevUmbracoPluginsPdfCuratorContentFilesPath>
  </PropertyGroup>
  <Target Name="CopySplatDevUmbracoPluginsPdfCuratorAssets" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <SplatDevUmbracoPluginsPdfCuratorContentFiles Include="$(SplatDevUmbracoPluginsPdfCuratorContentFilesPath)" />
    </ItemGroup>
    <Copy SourceFiles="@(SplatDevUmbracoPluginsPdfCuratorContentFiles)" DestinationFiles="@(SplatDevUmbracoPluginsPdfCuratorContentFiles-&gt;'$(MSBuildProjectDirectory)\wwwroot\App_Plugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
