using System.Text;
using SplatDev.Umbraco.Plugins.CustomLogin.Models;

namespace SplatDev.Umbraco.Plugins.CustomLogin.Services;

public static class LoginPageCssGenerator
{
    public static string Generate(CustomLoginSettings settings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by SplatDev.Umbraco.Plugins.CustomLogin */");
        sb.AppendLine(":root {");

        AppendProperty(sb, "--umb-login-background", settings.BackgroundColor);
        AppendProperty(sb, "--umb-login-primary-color", settings.PrimaryColor);
        AppendProperty(sb, "--umb-login-text-color", settings.TextColor);
        AppendProperty(sb, "--umb-login-curves-color", settings.CurvesColor);

        if (!settings.ShowCurves)
            sb.AppendLine("  --umb-login-curves-display: none;");

        if (!settings.ShowImagePanel)
            sb.AppendLine("  --umb-login-image-display: none;");

        if (!string.IsNullOrWhiteSpace(settings.BackgroundImageUrl))
            sb.AppendLine($"  --umb-login-image: url('{settings.BackgroundImageUrl}');");

        AppendProperty(sb, "--umb-login-image-border-radius", settings.ImageBorderRadius);
        AppendProperty(sb, "--umb-login-content-background", settings.ContentBackground);
        AppendProperty(sb, "--umb-login-content-width", settings.ContentWidth);
        AppendProperty(sb, "--umb-login-content-height", settings.ContentHeight);
        AppendProperty(sb, "--umb-login-content-border-radius", settings.ContentBorderRadius);
        AppendProperty(sb, "--umb-login-align-items", settings.AlignItems);
        AppendProperty(sb, "--umb-login-header-font-size", settings.HeaderFontSize);
        AppendProperty(sb, "--umb-login-header-font-size-large", settings.HeaderFontSizeLarge);
        AppendProperty(sb, "--umb-login-header-secondary-font-size", settings.HeaderSecondaryFontSize);
        AppendProperty(sb, "--umb-login-button-border-radius", settings.ButtonBorderRadius);

        sb.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(settings.TimeoutBackgroundImageUrl))
        {
            sb.AppendLine();
            sb.AppendLine("/* Timeout / session-expired screen override */");
            sb.AppendLine("umb-auth-layout[flow-is-not='login'] {");
            sb.AppendLine($"  --umb-login-image: url('{settings.TimeoutBackgroundImageUrl}');");
            sb.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(settings.FooterText))
        {
            sb.AppendLine();
            sb.AppendLine("/* Footer text overlay */");
            sb.AppendLine("umb-auth-layout::after {");
            sb.AppendLine($"  content: \"{EscapeCssString(settings.FooterText)}\";");
            sb.AppendLine("  position: fixed; bottom: 8px; left: 0; right: 0;");
            sb.AppendLine("  text-align: center; font-size: 0.75rem; opacity: 0.7;");
            sb.AppendLine("  pointer-events: none; z-index: 1000;");
            sb.AppendLine("}");
        }

        if (!string.IsNullOrWhiteSpace(settings.CustomCss))
        {
            sb.AppendLine();
            sb.AppendLine("/* Custom CSS overrides */");
            sb.AppendLine(settings.CustomCss);
        }

        return sb.ToString();
    }

    private static void AppendProperty(StringBuilder sb, string property, string value)
    {
        if (!string.IsNullOrWhiteSpace(value))
            sb.AppendLine($"  {property}: {value};");
    }

    private static string EscapeCssString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\A ").Replace("\r", "");
}
