using System.Text;
using SplatDev.Umbraco.Plugins.CustomLogin.Models;

namespace SplatDev.Umbraco.Plugins.CustomLogin.Services;

public static class LoginPageLocalizationGenerator
{
    private static readonly string[] DefaultGreetingsEn =
    [
        "Happy Sunday",
        "Happy Monday",
        "Happy Tuesday",
        "Happy Wednesday",
        "Happy Thursday",
        "Happy Friday",
        "Happy Saturday",
    ];

    private static readonly string[] DefaultGreetingsEs =
    [
        "Feliz domingo",
        "Feliz lunes",
        "Feliz martes",
        "Feliz miércoles",
        "Feliz jueves",
        "Feliz viernes",
        "Feliz sábado",
    ];

    public static string GenerateEnglish(CustomLoginSettings settings)
    {
        return GenerateModule(settings.Greetings, DefaultGreetingsEn, settings.TimeoutInstructionText);
    }

    public static string GenerateSpanish(CustomLoginSettings settings)
    {
        return GenerateModule(settings.GreetingsEs, DefaultGreetingsEs, settings.TimeoutInstructionTextEs);
    }

    private static string GenerateModule(string[] greetings, string[] defaults, string timeoutInstruction)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by SplatDev.Umbraco.Plugins.CustomLogin");
        sb.AppendLine("export default {");
        sb.AppendLine("  auth: {");

        for (var i = 0; i < 7; i++)
        {
            var greeting = greetings is { Length: > 0 } && i < greetings.Length && !string.IsNullOrWhiteSpace(greetings[i])
                ? greetings[i]
                : defaults[i];
            sb.AppendLine($"    greeting{i}: \"{EscapeJs(greeting)}\",");
        }

        if (!string.IsNullOrWhiteSpace(timeoutInstruction))
            sb.AppendLine($"    instruction: \"{EscapeJs(timeoutInstruction)}\",");

        sb.AppendLine("  },");
        sb.AppendLine("};");
        return sb.ToString();
    }

    public static string GenerateV13Xml(CustomLoginSettings settings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>");
        sb.AppendLine("<language culture=\"en-US\">");
        sb.AppendLine("  <area alias=\"login\">");

        for (var i = 0; i < 7; i++)
        {
            var greeting = settings.Greetings is { Length: > 0 } && i < settings.Greetings.Length && !string.IsNullOrWhiteSpace(settings.Greetings[i])
                ? settings.Greetings[i]
                : DefaultGreetingsEn[i];
            sb.AppendLine($"    <key alias=\"greeting{i}\">{System.Security.SecurityElement.Escape(greeting)}</key>");
        }

        sb.AppendLine("  </area>");
        sb.AppendLine("</language>");
        return sb.ToString();
    }

    private static string EscapeJs(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
}
