#!/usr/bin/env python3
"""Generate the Directory.Build.props that the staging image builds against.

infra/testing-instances/u17/Dockerfile installs every plugin in one restore by copying this
file in as Directory.Build.props. It has always said "Regenerate with make-props.py", and
that script did not exist - the props file was maintained by hand, so a plugin added to the
repo never reached the testing instance until someone remembered to edit it.

Discovery mirrors publish.yml exactly, so a package that ships is a package staging gets.
A project with IsPackable=false emits no .nupkg, so packing is what decides membership -
this only lists what is actually there, and reports anything it expected but did not find.
"""
import argparse, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Same rule as publish.yml's discovery, kept in one place so the two cannot drift.
EXCLUDE = re.compile(r"Tests|BackupManager|FormsClone|obj|bin|/customers/|test-environments")


def expand(value, text, fallback):
    """Resolve $(Prop) against <Prop> elements in the same file.

    Schema2Yaml declares <PackageId>$(_BasePackageId)</PackageId> so that a themed variant
    can append to it, and a plain regex read of PackageId yields the literal "$(_BasePackageId)".
    That went into plugins.props verbatim and the restore would have looked for a package by
    that name. Resolve what the file itself defines, and fall back to the project name - which
    ARCHITECTURE.md requires to equal the package id anyway.
    """
    for _ in range(3):
        if "$(" not in value:
            return value
        def sub(m):
            found = re.search(rf"<{re.escape(m.group(1))}>([^<]*)</{re.escape(m.group(1))}>", text)
            return found.group(1) if found else m.group(0)
        new_value = re.sub(r"\$\(([A-Za-z_][A-Za-z0-9_]*)\)", sub, value)
        if new_value == value:
            break
        value = new_value
    return fallback if "$(" in value else value


def discover():
    out = []
    for csproj in sorted(ROOT.glob("*/*.csproj")) + sorted(ROOT.glob("*/*/*.csproj")):
        rel = csproj.relative_to(ROOT).as_posix()
        if not csproj.name.startswith("SplatDev.") or EXCLUDE.search("/" + rel):
            continue
        text = csproj.read_text(encoding="utf-8", errors="replace")
        if re.search(r"<IsPackable>\s*false\s*</IsPackable>", text, re.I):
            continue
        # A dotnet tool is installed with `dotnet tool install`, not referenced. Listing one
        # fails the restore outright with NU1212 ("DotnetToolReference project style can only
        # contain references to packages of type DotnetTool"), which is where the second live
        # deploy stopped - on SplatDev.Umbraco.Tools.Packager.
        if re.search(r"<PackAsTool>\s*true\s*</PackAsTool>", text, re.I) or \
           re.search(r"<PackageType>\s*DotnetTool", text, re.I):
            continue

        # The instance is net10.0. A package that never targets it fails the restore, so a
        # net8-only project must not be listed however publishable it is.
        tfms = re.search(r"<TargetFrameworks?>([^<]+)</TargetFrameworks?>", text)
        if not tfms or "net10.0" not in tfms.group(1):
            continue
        version = re.search(r"<Version>([^<]+)</Version>", text)
        pkg_id = re.search(r"<PackageId>([^<]+)</PackageId>", text)
        if not version:
            continue
        name = pkg_id.group(1) if pkg_id else csproj.stem
        out.append((expand(name, text, csproj.stem), version.group(1)))
    return out


def render(pkgs):
    """Emit the props file in Central Package Management form.

    The Umbraco 17 template enables CPM, under which a PackageReference carrying a Version
    is an error, not a preference - the first live deploy died on NU1008 listing every one
    of these packages. Versions go in PackageVersion items instead, and the reference itself
    is bare. ManagePackageVersionsCentrally is asserted here rather than assumed, because
    Directory.Build.props is imported before Directory.Packages.props, so a condition on it
    would evaluate before the template had set it.
    """
    lines = [
        "<!-- Generated by tools/make-plugins-props.py. Do not edit by hand. -->",
        "<!-- Copied into the staging image as Directory.Build.props: one restore covers",
        "     every plugin, where a `dotnet add package` each turns a two-minute build",
        "     into an hours-long one. -->",
        "<Project>",
        "",
        "  <PropertyGroup>",
        "    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>",
        "  </PropertyGroup>",
        "",
        "  <ItemGroup>",
    ]
    for pkg, _ in pkgs:
        lines.append(f'    <PackageReference Include="{pkg}" />')
    lines += ["  </ItemGroup>", "", "  <ItemGroup>"]
    for pkg, ver in pkgs:
        lines.append(f'    <PackageVersion Include="{pkg}" Version="{ver}" />')
    lines += ["  </ItemGroup>", "", "</Project>", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "infra/testing-instances/u17/plugins.props"))
    ap.add_argument("--packages-dir", help="only list plugins with a .nupkg here, and fail on any missing")
    ap.add_argument("--check", action="store_true", help="exit 1 if the file on disk is stale")
    args = ap.parse_args()

    pkgs = discover()
    if args.packages_dir:
        have = {p.name for p in pathlib.Path(args.packages_dir).glob("*.nupkg")}
        missing = [(p, v) for p, v in pkgs if f"{p}.{v}.nupkg" not in have]
        if missing:
            # Silence here would mean the instance quietly tests fewer plugins than it claims.
            for p, v in missing:
                print(f"::error::no package for {p} {v} in {args.packages_dir}")
            return 1

    rendered = render(pkgs)
    out = pathlib.Path(args.out)
    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != rendered:
            print(f"{out} is stale; run tools/make-plugins-props.py")
            return 1
        print(f"{out} is up to date ({len(pkgs)} packages).")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    print(f"wrote {out} with {len(pkgs)} package(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
